default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Atef2004
  host: db
  port: 5432

development:
  <<: *default
  database: todo_backend_development
