name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # Set the working directory to backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Replace with your project's Ruby version
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: bundle exec rubocop
